const EventDetails = [
  {
    id: 1,
    img: "../imgs/dcode.jpg",
    title: "GG",
    desc: "Coding is an integral part of Robotics. Our coding event is designed to be both challenging and fun During this event, you will have the chance to compete with other talented programmers and solve challenging coding problems. The winners will be determined based on accuracy, efficiency, and speed. ",
    ev: "Lab",
    et: "10.30 am",
    ts: "2",
  },
  {
    id: 2,
    img: "../imgs/arduinoclash.jpg",
    title: "Arduino Clash",
    desc: "Welcome to our Arduino event! This is a fantastic opportunity for electronics enthusiasts to demonstrate your skills and knowledge by performing simple tasks using Arduino. Participants will have to go through a written test. The selected teams have to complete a task based on Arduino. The team conceding minimum time will be the winner.",
    ev: "Media Center",
    et: "10.30 am",
    ts: "3",
  },
  {
    id: 3,
    img: "../imgs/ruggedrace.jpg",
    title: "Rugged Race",
    desc: "Each participant has to design and build a manually controlled wired/wireless bot. During this event your robots will face various obstacles, such as navigating through rough terrain, climbing over obstacles, and crossing water barriers. The course is designed to test your robot's strength, speed, and adaptability as they go through challenging terrain. ",
    ev: "Outdoor Stadium",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 4,
    img: "../imgs/robosoccer.jpg",
    title: "Robo Soccer",
    desc: "The objective is to design a manual robot which can compete compete against each other in a soccer arena. It will be a one vs one soccer match in which the aim will be to push the ball in the opponent's goal post. Our Robo Soccer event is designed to be both challenging and entertaining, providing you with the opportunity to win some fantastic prizes. ",
    ev: "Canteen",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 5,
    img: "../imgs/lfr.jpg",
    title: "LFR",
    desc: "Fumble and it’s all over!! Trace it and track the prize!!! This event is for the code masters. Here’s your chance to prove your robot’s worth. A series of simple yet complex path are to be traced by the autonomous robot. Build the right circuit and test the precision of your programming. And as the saying goes, You don’t fall out of track and you shall emerge victorious. ",
    ev: "Indoor Stadium",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 6,
    img: "../imgs/bluetooth.jpg",
    title: "Bluetooth",
    desc: "Gear up for rumbling engines, flamboyant wireless cars and adrenaline packed races at the all new Cross Roads. It's all about speed, control and accuracy, the bot that covers the track in the minimum time collecting the maximum points will be the champion. Now put effort into competition and conquer the field. ",
    ev: "Canteen",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 7,
    img: "../imgs/paperpresentation.jpg",
    title: "Paper Presentation",
    desc: " It’s time to show who’s the boss when it comes to the command over the subject. If you have an idea which has been taking shelter in your mind that  would change lifestyles visibly,make inroads into the development of geeky  technology or even make some known technology effective and efficient then  we offer you the stage to showwho you are to the world. ",
    ev: "Seminar Hall",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 8,
    img: "../imgs/projectsymposium.jpg",
    title: "Project Symposium",
    desc: "Are you ready to show your skills? A Platform to build, develop and showcase your ideas. The staple diet of all technical events is undoubtedly the presentation event, yet it has something in it which makes it exciting . Sweat your mind and work to innovate the future.take out your imagination into the real world and experience  the unique satisfaction of ur dream come true. ",
    ev: "Seminar hall",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 9,
    img: "../imgs/spardha.jpg",
    title: "Spardha",
    desc: "It's a fun event. You can activate the child inside you. Feel energetic and refreshed after participating. Go through the series of challenges under one roof , its just like a magician’s hat , which is full of fun and crazy enthusiastic sub events each one unique in its own league take out your inner child and unleash your hunger for fun in this event . Now there is nothing to hold back go and participate NOW.",
    ev: "Architecture dept.",
    et: "10.30 am",
    ts: "2",
  },
  {
    id: 10,
    img: "../imgs/group.jpg",
    title: "Group photo",
    desc: "It's a photo clicked in the end of the event. It depicts the successful conduction of event. It'll have all members form Corsit who had taken part in Robocor. It shows the team work of the members and the efforts put in to make the event successful. Here we'll get to see the hardwork and the smartwork done by club members from the past few months in the form of a grand event.",
    ev: "Media Center",
    et: "10.30 am",
    ts: "53",
  },
];
export default EventDetails;
