const EventDetails = [
  {
    id: 1,
    img: "../imgs/dino.png",
    title: "Decode",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. It will be an all India competition you will be able to find out your place in the crowd of elite coders sitting just beside you in the competition . self evaluation plays a very major role in improving yourself.",
    ev: "Lab",
    et: "10.30 am",
    ts: "2",
  },
  {
    id: 2,
    img: "../imgs/dino.png",
    title: "Arduino Clash",
    desc: "Come, let out the inventive genius in you. In this event, participants will have to go through a written test. The selected teams have to complete a task based on Arduino. The team conceding minimum time will be the winner. Competitions such as arduino clash helps you to develop your on spot problem solving skills. is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",
    ev: "Media Center",
    et: "10.30 am",
    ts: "3",
  },
  {
    id: 3,
    img: "../imgs/dino.png",
    title: "Rugged Race",
    desc: "The objective is to design a manual robot which can compete on an arena specially designed for robotic soccer match. It will be a one vs one soccer match in which the aim will be to push the ball in the opponent's goal post. The most dexterous and quirky design prevail. Just experience the sumo clash of amazing bots in the field.  is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",
    ev: "Outdoor Stadium",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 4,
    img: "../imgs/dino.png",
    title: "Robo Soccer",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    ev: "Canteen",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 5,
    img: "../imgs/dino.png",
    title: "LFR",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    // desc: "Fumble and it is all over!! Trace it and track the prize!!! This event is for the codemasters. Here’s your chance to prove your robot’s worth. A series of simple yet complex path are to be traced by the autonomous robot. Build the right circuit and test the precision of your programming. And as the saying goes, You don’t fall out of track and you shall emerge victorious, stay on line and pave the path to success!!! ",
    ev: "Indoor Stadium",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 6,
    img: "../imgs/dino.png",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    title: "Bluetooth",
    // desc: "Gear up for rumbling engines, flamboyant wireless cars and adrenaline packed races at the all new Cross Roads. It's all about speed, control and accuracy, the bot that covers the track in the minimum time collecting the maximum points will be the champion. ",
    ev: "Canteen",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 7,
    img: "../imgs/dino.png",
    title: "Paper Presentation",
    ev: "Seminar Hall",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 8,
    img: "../imgs/dino.png",
    title: "Project Symposium",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    // desc: "Are you ready to show your skills? A Platform to build, develop and showcase your ideas. Sweat your mind and work to innovate the future. ",
    ev: "Seminar hall",
    et: "10.30 am",
    ts: "4",
  },
  {
    id: 9,
    img: "../imgs/dino.png",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    title: "Spardha",
    // desc: "It's a fun event. You can activate the child inside you. Feel energetic and refreshed after participating. What are you waiting for,Register now...",
    ev: "Architecture dept.",
    et: "10.30 am",
    ts: "2",
  },
  {
    id: 10,
    img: "../imgs/dino.png",
    title: "Group photo",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",

    // desc: "It's a photo clicked in the end.",
    ev: "Media Center",
    et: "10.30 am",
    ts: "53",
  },
];
export default EventDetails;
