const EventDetails = [
  {
    id: 1,
    img: "../imgs/Decode1.JPG",
    title: "Decode",
    desc: "Coding is an integral part of Robotics. This event encourages students from all branches to participate and improve their coding and critical thinking skill. ",
    ev:"Lab",
    et:"10.30",
    ts:"2",
  },
  {
    id: 2,
    img: "../imgs/ArduinoClash1.JPG",
    title: "Arduino Clash",
    desc: "Come, let out the inventive genius in you. In this event, participants will have to go through a written test. The selected teams have to complete a task based on Arduino. The team conceding minimum time will be the winner. ",
    ev:"Media Center",
    et:"10.30",
    ts:"3",
  },
  {
    id: 3,
    img: "../imgs/RuggedRace1.JPG",
    title: "Rugged Race",
    desc: "Each participant has to design and build a manually controlled wired/wireless bot that is capable of traversing a given terrain with ease and in less time. The arena is designed to test the mobility and speed of the bot in various terrains. ",
    ev:"Outdoor Stadium",
    et:"10.30",
    ts:"4",
  },
  {
    id: 4,
    img: "../imgs/RoboSoccer1.JPG",
    title: "Robo Soccer",
    desc: "The objective is to design a manual robot which can compete on an arena specially designed for robotic soccer match. It will be a one vs one soccer match in which the aim will be to push the ball in the opponent's goal post. The most dexterous and quirky design prevail. ",
    ev:"Canteen",
    et:"10.30",
    ts:"4",
  },
  {
    id: 5,
    img: "../imgs/LFR1.JPG",
    title: "LFR",
    desc: "Fumble and it is all over!! Trace it and track the prize!!! This event is for the codemasters. Here’s your chance to prove your robot’s worth. A series of simple yet complex path are to be traced by the autonomous robot. Build the right circuit and test the precision of your programming. And as the saying goes, You don’t fall out of track and you shall emerge victorious, stay on line and pave the path to success!!! ",
    ev:"Indoor Stadium",
    et:"10.30",
    ts:"4",
  },
  {
    id: 6,
    img: "../imgs/Bluetooth1.jpeg",
    title: "Bluetooth",
    desc: "Gear up for rumbling engines, flamboyant wireless cars and adrenaline packed races at the all new Cross Roads. It's all about speed, control and accuracy, the bot that covers the track in the minimum time collecting the maximum points will be the champion. ",
    ev:"Canteen",
    et:"10.30",
    ts:"4",
  },
  {
    id: 7,
    img: "../imgs/PaperPresentaion1.JPG",
    title: "Paper Presentation",
    desc: "It’s time to show who’s the boss when it comes to the command over the subject. The staple diet of all technical events is undoubtedly the presentation event, yet it has something in it which makes it exciting. If you have an idea which has been taking shelter in your mind that would change lifestyles visibly, make inroads into the development of geeky technology or even make some known technology effective and efficient then we offer you the stage to show who you are to the world. ",
    ev:"Seminar Hall",
    et:"10.30",
    ts:"4",
  },
  {
    id: 8,
    img: "../imgs/ProjectSymposium1.JPG",
    title: "Project Symposium",
    desc: "Are you ready to show your skills? A Platform to build, develop and showcase your ideas. Sweat your mind and work to innovate the future. ",
    ev:"Seminar hall",
    et:"10.30",
    ts:"4",
  },
  {
    id: 9,
    img: "../imgs/Spardha1.jpeg",
    title: "Spardha",
    desc: "It's a fun event. You can activate the child inside you. Feel energetic and refreshed after participating. What are you waiting for,Register now...",
    ev:"Architecture dept.",
    et:"10.30",
    ts:"2",
  },
  {
    id: 10,
    img: "../imgs/Group1.jpeg",
    title: "Group photo",
    desc: "It's a photo clicked in the end.",
    ev:"Media Center",
    et:"10.30",
    ts:"53",
  },
];
export default EventDetails;
